version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        environment:
          FLASK_CONFIG: testing
          TEST_DATABASE_URL: postgresql://ubuntu@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ''
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: |
            java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
      - restore_cache:
          key: deps2-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
      - save_cache:
          key: deps2-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - 'venv'
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "$CIRCLE_BRANCH" == "qa" ]; then
               git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$QA_HEROKU_APP.git qa:master
            elif [ "$CIRCLE_BRANCH" == "staging" ]; then
               git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$STAGING_HEROKU_APP.git staging:master
            elif [ "$CIRCLE_BRANCH" == "master" ]; then
               git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$PRODUCTION_HEROKU_APP.git master
            else
              echo "Deploy only for qa, staging, master branches."
            fi
